### ISSUE TITLE
Upgrade Catalog Tool and dependencies to support Harvest/Registry upgrades

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-pds3-catalog#4]
## 💡 Description

- https://github.com/NASA-PDS/registry-pds3-catalog/issues/2

**Comment by nutjob4life** [comment]
Tagging with

    git tag --annotate --message "Release of 2.1.0" release/2.1.0
    git push origin release/2.1.0

**Comment by jordanpadams** [comment]
Closing this as good for now. Testing will be noted elsewhere
